Ajuste a los cambios de la web

diff --git a/dxtotal b/dxtotal
--- a/dxtotal
+++ b/dxtotal
@@ -4,7 +4,7 @@ SERVER="192.168.0.10:9091 --auth admin:admin"
 DIR=~/bin/scripts/series/titles/
 LOGFILE=~/bin/scripts/dxtotal/log
 WEBADDRESS="www.divxtotal2.net"
-SERIESURI="series"
+SERIESURI="serie"
 
 VERSION="1.2.1"
 
@@ -222,6 +222,11 @@ function check {
 	folder=`cat "$DIR$series"`
 	#Como quitamos "magnet:" de la cadena, después tenemos que aádir magnet:
 	transmission-remote $SERVER --add "/tmp/torrent.torrent" --download-dir "$folder"
+
+	if [[ $? != 0 ]]; then
+		echo "ERROR: No se ha podido añadir el torrent"
+		echo "Asegurate de que transmission esté en funcionamiento"
+	fi
 
 	#Registramos la descarga
 	log "$name"
